/**
 * Generated by the Croct CLI.
 *
 * Any manual changes will be overwritten.
 *
 * To regenerate, run `croct update`.
 */

/**
 * Features section
 */
type Def$ab2b8ab9 = {
  /**
   * Heading
   */
  'heading': string,
  /**
   * Tagline
   */
  'tagline': string,
  /**
   * Features
   */
  'features': Array<{
    /**
     * Icon
     */
    'icon': string,
    /**
     * Title
     */
    'title': string,
    /**
     * Description
     */
    'description': string,
  }>,
  /**
   * Description
   */
  'description': string,
};

/**
 * Home hero
 */
type Def$0ff0dd68 = {
  /**
   * Title
   */
  'title': string,
  /**
   * Details
   */
  'details'?: string,
  /**
   * Tagline
   */
  'tagline'?: string,
  /**
   * Primary CTA
   */
  'primaryCta': {
    /**
     * URL
     */
    'url': string,
    /**
     * Label
     */
    'label': string,
  },
  /**
   * Description
   */
  'description'?: string,
  /**
   * Secondary CTA
   */
  'secondaryCta'?: {
    /**
     * URL
     */
    'url': string,
    /**
     * Label
     */
    'label': string,
  },
};

type Def$ca23403c = {
  /**
   * Steps
   */
  'steps': Array<{
    /**
     * Title
     */
    'title': string,
    /**
     * Step number
     */
    'stepNumber': number,
    /**
     * Description
     */
    'description': string,
  }>,
  /**
   * Heading
   */
  'heading': string,
  /**
   * Tagline
   */
  'tagline'?: string,
  /**
   * Description
   */
  'description'?: string,
};

declare module '@croct/plug/slot' {
  type FeaturesSectionV2 = Def$ab2b8ab9 & {'_component': 'features-section@2' | null};
  type HomeHeroV1 = Def$0ff0dd68 & {'_component': 'home-hero@1' | null};
  type HowItWorksSectionV1 = Def$ca23403c & {'_component': 'how-it-works-section@1' | null};
  
  export interface VersionedSlotMap {
    'features-section': {
      latest: FeaturesSectionV2,
      '2': FeaturesSectionV2,
    };

    'home-hero': {
      latest: HomeHeroV1,
      '1': HomeHeroV1,
    };

    'how-it-works-section': {
      latest: HowItWorksSectionV1,
      '1': HowItWorksSectionV1,
    };
  }
}

export {};